coverage:
  status:
    project:
      default:
        # basic
        target: 94%
        threshold: 0%
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
    patch:
      default:
        # basic
        target: 94%
        threshold: 0%
        # advanced settings
        if_ci_failed: error
        informational: false
